### ISSUE TITLE
增加格式美化功能

### ISSUE THREAD

**Issue by sdfcbs91** [xingw-z/vite-plugin-raw#1]
这个插件很棒!! 解决了获取源代码的问题.
可否加一个功能选项：格式美化。

比如这种 `<template>\n  <div class="tpl">\n    <ActFunctionSetting>\n      <LinkSeePaasTaskSystemTable\n        ref="content"\n        slot-scope="data"\n        :tasksystem="tasksystem"\n        :indicators="data.indicators"\n        :gift-group-list="data.giftGroupList"\n        pid="11"\n        :check-info="{datamore_id:12}"\n      />\n    </ActFunctionSetting>\n  </div>\n</template>\n\x3Cscript>\nimport { tasksystem } from './data';\nexport default {\n  data() {\n    return {\n      tasksystem: undefined,\n    };\n  },\n  mounted() {\n    setTimeout(() => {\n      this.tasksystem = tasksystem;\n      this.setFormData(this.tasksystem);\n    }, 200);\n  },\n  methods: {\n    setFormData(data) {\n      const content = this.$refs.content;\n      if (content && content.setFormData) {\n        content.setFormData(data);\n      }\n    },\n  },\n};\n\x3C/script>\n`

**Comment by xingw-z** [comment]
这是把读取到文件后的字符串再进行格式化吗，不太明白这个场景，但是我理解你应该使用插件后获得结果再进行格式化应该就能达到这个目的了吧。

**Comment by xingw-z** [comment]
结束
